version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: agroer_postgres
    environment:
      POSTGRES_DB: Agroer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - agroer_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Agroer"]
      interval: 30s
      timeout: 10s
      retries: 3

  # pgAdmin para gerenciamento do banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: agroer_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agroer.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - agroer_network
    depends_on:
      - postgres

  # Agente1 - Processamento PDF
  agente1:
    build:
      context: ../agente1
      dockerfile: Dockerfile
    container_name: agroer_agente1
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
        - ./agente1.env.docker
    networks:
      - agroer_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Agente2 - Validação e Banco
  agente2:
    build:
      context: ../agente2
      dockerfile: Dockerfile
    container_name: agroer_agente2
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=Agroer
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - FRONTEND_URL=http://frontend:5173
    env_file:
      - ./agente2.env.docker
    networks:
      - agroer_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: agroer_frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_AGENTE1_URL=http://agente1:3001
      - VITE_AGENTE2_URL=http://agente2:3002
    networks:
      - agroer_network
    env_file:
      - ./.env.docker
    depends_on:
      - agente1
      - agente2
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  agroer_network:
    driver: bridge